language: php

install:
    - composer install

jobs:
    include:
        - stage: CI on 7.4
          script: make ci
          php: '7.4'

        - stage: CI on 8.0
          script: make ci
          php: '8.0'

        - stage: Functional Tests
          script: make functional
          php:
              - '7.4'

after_success:
    - bash <(curl -s https://codecov.io/bash) -f "build/coverage.xml"

env:
    global:
        - XDEBUG_MODE=coverage
