language: php
php:
    - '7.4'

install:
    - composer install

jobs:
    include:
        - stage: CI
          script: make ci

        - stage: Functional Tests
          script: make functional

after_success:
    - bash <(curl -s https://codecov.io/bash)
