language: php

install:
    - composer install

jobs:
    include:
        - stage: CI
          script: make ci
          php:
              - '7.4'
              - '8.0'

        - stage: Functional Tests
          script: make functional
          php:
              - '7.4'
              - '8.0'

after_success:
    - bash <(curl -s https://codecov.io/bash) -f "build/coverage.xml"

env:
    global:
        - XDEBUG_MODE=coverage
