language: php
php:
    - '7.4'

install:
    - composer install

branches:
    only:
        - master

jobs:
    include:
        - stage: CI
          script: make ci

        - stage: Functional Tests
          script: make functional
