codecov:
    require_ci_to_pass: true

coverage:
    status:
        patch: off
        project:
            default:
                target: 90.5%
                threshold: 0%
                base: auto
                if_ci_failed: error
                paths:
                    - "src"
comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false
    require_base: false        # [yes :: must have a base report to post]
    require_head: true       # [yes :: must have a head report to post]
