name: CI

on: [pull_request]

jobs:
    ci:
        runs-on: ubuntu-20.04
        env:
            APP_ENV: test
            XDEBUG_MODE: coverage

        strategy:
            matrix:
                php-versions: ['7.4', '8.0']

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
            -   run: cp phpunit.xml.dist phpunit.xml
            -   run: composer install
            -   run: make ci
            -   run: bash <(curl -s https://codecov.io/bash) -f "var/coverage/coverage.xml" -t $CODECOV_TOKEN
