name: CI

on:
    pull_request:
        branches:
            - master

jobs:
    ci:
        runs-on: ubuntu-20.04
        strategy:
            max-parallel: 1
            matrix:
                php-version: [ '7.4', '8.0' ]
        concurrency:
            group: ci-${{ github.ref }}-${{ matrix.php-version }}
            cancel-in-progress: true
        env:
            WFIRMA_API_COMPANY: ${{ secrets.WFIRMA_API_COMPANY }}
            WFIRMA_API_LOGIN: ${{ secrets.WFIRMA_API_LOGIN }}
            WFIRMA_API_PASSWORD: ${{ secrets.WFIRMA_API_PASSWORD }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
            -   name: composer install
                run: composer install
            -   name: make ci
                run: make ci
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: var/coverage/coverage.xml
